workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v8
      - node-v10
      - node-latest

version: 2
jobs:
  base: &base
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
      - run: git@github.com:Leko/node.git
      - run: cd node && node ../index.js
  node-latest:
    <<: *base
    docker:
      - image: node:latest
  node-v8:
    <<: *base
    docker:
      - image: node:8
  node-v10:
    <<: *base
    docker:
      - image: node:10
