workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v8
      - node-v10
      - node-v12
      - node-latest
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - node-v8
            - node-v10
            - node-v12
            - node-latest

version: 2
jobs:
  base: &base
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
      - run: git clone --depth=1 git@github.com:Leko/node.git
      - run: cd node && node ../index.js --help
      - run: cd node && node ../index.js --set
      - run: cd node && node ../index.js --set -f
      - run: cd node && node ../index.js --set -f --https
      - run: cd node && node ../index.js --set -f --no-shallow
      - run: rm -rf node # clean up
  node-latest:
    <<: *base
    docker:
      - image: node:latest
  node-v8:
    <<: *base
    docker:
      - image: node:8
  node-v10:
    <<: *base
    docker:
      - image: node:10
  node-v12:
    <<: *base
    docker:
      - image: node:12
  deploy:
    <<: *base
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-{{ checksum "package-lock.json" }}
      - run: npx semantic-release
